---
- name: Reset RKE2 cluster
  hosts: rke2_cluster
  gather_facts: true
  tasks:
    - name: Stop RKE2 services
      systemd:
        name: rke2-server
        state: stopped
        enabled: no
      become: true
    - name: Clean up RKE2 data
      file:
        path: /var/lib/rancher/rke2
        state: absent
      become: true
    - name: Reboot and wait for node to come back up
      reboot:
        reboot_command: "{{ custom_reboot_command | default(omit) }}"
        reboot_timeout: 3600
      become: true
