---
- name: Get the list of mounted filesystems
  shell: |
    set -o pipefail && \
    awk '{ print $2 }' /proc/mounts | grep -E "^{{ mounted_fs }}"
  register: get_mounted_filesystems
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: get_mounted_filesystems.stdout | length > 0
  check_mode: false

- name: Umount filesystem
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ get_mounted_filesystems.stdout_lines | reverse | list }}"
  when: get_mounted_filesystems.stdout | length > 0
