---
- name: Verify RKE2 Cluster with Cilium
  hosts: all
  tasks:
    - name: Check if all nodes are Ready
      shell: kubectl get nodes
      register: result
    - name: Print node status
      debug:
        msg: "{{ result.stdout }}"
    - name: Check if kube-vip is running
      shell: kubectl get pods -n kube-system | grep kube-vip
      register: kube_vip_result
    - name: Print kube-vip status
      debug:
        msg: "{{ kube_vip_result.stdout }}"
    - name: Check if MetalLB is running
      shell: kubectl get pods -n metallb-system
      register: metallb_result
    - name: Print MetalLB status
      debug:
        msg: "{{ metallb_result.stdout }}"
    - name: Check if Cilium is running
      shell: kubectl get pods -n kube-system | grep cilium
      register: cilium_result
    - name: Print Cilium status
      debug:
        msg: "{{ cilium_result.stdout }}"
